language: node_js
node_js:
  - "6"
  - "stable"

script:
  - npm run lint
  - npm run test
  - npm run pack

deploy:
  - provider: script
    script: npm run publish
    on:
      branch: master

notifications:
  email:
    on_success: never
    on_failure: change