language: node_js
node_js: "6.10"

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - npm run lint
  - npm run test
  - npm run pack

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
    condition: "$TRAVIS_EVENT_TYPE != 'cron'"

notifications:
  email:
    on_success: never
    on_failure: always